retry

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -280,8 +280,11 @@ jobs:
 
       - name: Install dependencies
         run: |
-          sudo pkg install -y dejavu gettext gtk4 python311 py311-build py311-pygobject \
-            py311-setuptools py311-wheel
+          # Retry up to three times due to sporadic errors fetching packages
+          for i in {1..3}; do
+            bash -c "sudo pkg install -y dejavu gettext gtk4 python311 py311-build py311-pygobject \
+              py311-setuptools py311-wheel" && break || true
+          done
 
       - name: Integration and unit tests
         run: python3.11 -m unittest -v
